print (Hello world)
print ("Changes")
print ("second changes")
print ("third changes")
print ("Final changes")
print ("Pull from remote to local")
print ("checking changes status")
print("First change")
print("Pull the changes")
